export * from './branch.service';
import { BranchService } from './branch.service';
export * from './collection.service';
import { CollectionService } from './collection.service';
export * from './identity.service';
import { IdentityService } from './identity.service';
export * from './itinerary.service';
import { ItineraryService } from './itinerary.service';
export * from './loanDetails.service';
import { LoanDetailsService } from './loanDetails.service';
export * from './loanType.service';
import { LoanTypeService } from './loanType.service';
export * from './member.service';
import { MemberService } from './member.service';
export * from './remarks.service';
import { RemarksService } from './remarks.service';
export * from './standardEntries.service';
import { StandardEntriesService } from './standardEntries.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [BranchService, CollectionService, IdentityService, ItineraryService, LoanDetailsService, LoanTypeService, MemberService, RemarksService, StandardEntriesService, UsersService];
