/**
 * ECollect
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreateLoanDetailsCommand { 
    memberCode?: string;
    principal?: number;
    interest?: number;
    penalties?: number;
    serviceFee?: number;
    notarialFee?: number;
    miscellaneousIncome?: number;
    total?: number;
    promiseToPayDate?: Date;
    remarks?: string;
    branchId?: number;
    loanTypeId?: number;
    collectorUserName?: string;
    loanStatusId?: number;
}