/**
 * ECollect
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreateMemberDetailsCommand { 
    memberCode?: string;
    firstName?: string;
    middleName?: string;
    lastName?: string;
    suffixName?: string;
    contactNumber?: string;
    emailAddress?: string;
    street?: string;
    barangay?: string;
    city?: string;
    province?: string;
    zipCode?: string;
    genderId?: number;
    memberTypeId?: number;
}