/**
 * ECollect
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateLoanDetailsCommand { 
    loanDetailsGuid?: string;
    id?: number;
    loanTypeId?: number;
    branchId?: number;
    interest?: number;
    penalties?: number;
    serviceFee?: number;
    miscellaneousIncome?: number;
    remarks?: string;
    collectorUserName?: string;
    releasedAmount?: number;
    releasedDate?: Date;
    maturityDate?: Date;
    dateEndorsed?: Date;
    daysTurnOver?: number;
    loanDetailsStatusId?: number;
    statusNumberOfDays?: number;
    outstandingPrincipalBalance?: number;
    updaidPrincipal?: number;
    collectionFee?: number;
    litigationFee?: number;
    totalBalance?: number;
    forwardingAccountsId?: number;
}